services:
  - type: web
    name: tabsirah
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir web_app app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
